export { setGetMetadata } from './config'
export { registerSupportLocales } from './locales/index'
export { default as ContactSectionItemLink } from './containers/ContactSectionItemLink'
export { default as EditContactDrawer } from './views/contacts/edit/EditContactDrawer'
export { default as EditReviewDrawer } from './views/reviews/edit/EditReviewDrawer'
export { default as ReviewSectionItemLink } from './containers/ReviewSectionItemLink'
export { default as SupportSection } from './containers/SupportSection'
export { useOpenContactDrawer } from './utils/useOpenContactDrawer'
export { useOpenReviewDrawer } from './utils/useOpenReviewDrawer'
export { useReviewPrompt } from './utils/useReviewPrompt'
